server:
  port: 7979

spring:
  application:
    name: music-streaming-app
  datasource:
    url: jdbc:postgresql://localhost:5432/music_app
    username: music_app
    password: music_app
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
       ddl-auto: update # Options: none, update, create, create-drop, validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect